# Use an official OpenJDK runtime as a parent image
FROM openjdk:17-alpine

# Set the working directory in the container
WORKDIR /app

# Copy the JAR file generated by Maven into the container at /app
COPY target/mfsl-*.jar /app/mfsl.jar

# Expose the port your Spring Boot application will run on
EXPOSE 8080

# Specify the command to run your Spring Boot application
CMD ["java", "-jar", "mfsl.jar"]
