# Use an official OpenJDK runtime as a parent image
FROM openjdk:17-alpine

# Set the working directory in the container
WORKDIR /app

# Copy the JAR file generated by Maven into the container at /app
COPY target/mfsl-0.0.1-SNAPSHOT.jar /app/mfsl-0.0.1-SNAPSHOT.jar

# Expose the port your Spring Boot application will run on
EXPOSE 8080

# Define an environment variable with any necessary configurations
# ENV SPRING_PROFILES_ACTIVE=production

# Specify the command to run your Spring Boot application
CMD ["java", "-jar", "mfsl-0.0.1-SNAPSHOT.jar"]
